// Hardcoded internal strings
#ifndef __TJS_ERROR_INC_H__
#define __TJS_ERROR_INC_H__
TJS_MSG_DECL_CONST(TJSInternalError, TJS_W("Internal error"))
TJS_MSG_DECL_CONST(TJSWarning, TJS_W("Warning: "))
TJS_MSG_DECL_CONST(TJSWarnEvalOperator, TJS_W("Non-global post-! operator is used (note that the post-! operator behavior is changed on TJS2 version 2.4.1)"))
TJS_MSG_DECL_CONST(TJSNarrowToWideConversionError, TJS_W("Cannot convert given narrow string to wide string"))
TJS_MSG_DECL_CONST(TJSVariantConvertError, TJS_W("Cannot convert the variable type (%1 to %2)"))
TJS_MSG_DECL_CONST(TJSVariantConvertErrorToObject, TJS_W("Cannot convert the variable type (%1 to Object)"))
TJS_MSG_DECL_CONST(TJSIDExpected, TJS_W("Specify an ID"))
TJS_MSG_DECL_CONST(TJSSubstitutionInBooleanContext, TJS_W("Substitution in boolean context (use form of '(A=B)!=0' to compare to zero)"))
TJS_MSG_DECL_CONST(TJSCannotModifyLHS, TJS_W("This expression cannot be used as a lvalue"))
TJS_MSG_DECL_CONST(TJSInsufficientMem, TJS_W("Insufficient memory"))
TJS_MSG_DECL_CONST(TJSCannotGetResult, TJS_W("Cannot get the value of this expression"))
TJS_MSG_DECL_CONST(TJSNullAccess, TJS_W("Accessing to null object"))
TJS_MSG_DECL_CONST(TJSMemberNotFound, TJS_W("Member \"%1\" does not exist"))
TJS_MSG_DECL_CONST(TJSMemberNotFoundNoNameGiven, TJS_W("Member does not exist"))
TJS_MSG_DECL_CONST(TJSNotImplemented, TJS_W("Called method is not implemented"))
TJS_MSG_DECL_CONST(TJSInvalidParam, TJS_W("Invalid argument"))
TJS_MSG_DECL_CONST(TJSBadParamCount, TJS_W("Invalid argument count"))
TJS_MSG_DECL_CONST(TJSInvalidType, TJS_W("Not a function or invalid method/property type"))
TJS_MSG_DECL_CONST(TJSSpecifyDicOrArray, TJS_W("Specify a Dictionary object or an Array object"))
TJS_MSG_DECL_CONST(TJSSpecifyArray, TJS_W("Specify an Array object"))
TJS_MSG_DECL_CONST(TJSStringDeallocError, TJS_W("Cannot free the string memory block"))
TJS_MSG_DECL_CONST(TJSStringAllocError, TJS_W("Cannot allocate the string memory block"))
TJS_MSG_DECL_CONST(TJSMisplacedBreakContinue, TJS_W("Cannot place \"break\" or \"continue\" here"))
TJS_MSG_DECL_CONST(TJSMisplacedCase, TJS_W("Cannot place \"case\" here"))
TJS_MSG_DECL_CONST(TJSMisplacedReturn, TJS_W("Cannot place \"return\" here"))
TJS_MSG_DECL_CONST(TJSStringParseError, TJS_W("Un-terminated string/regexp/octet literal"))
TJS_MSG_DECL_CONST(TJSNumberError, TJS_W("Cannot be parsed as a number"))
TJS_MSG_DECL_CONST(TJSUnclosedComment, TJS_W("Un-terminated comment"))
TJS_MSG_DECL_CONST(TJSInvalidChar, TJS_W("Invalid character \'%1\'"))
TJS_MSG_DECL_CONST(TJSExpected, TJS_W("Expected %1"))
TJS_MSG_DECL_CONST(TJSSyntaxError, TJS_W("Syntax error (%1)"))
TJS_MSG_DECL_CONST(TJSPPError, TJS_W("Error in conditional compiling expression"))
TJS_MSG_DECL_CONST(TJSCannotGetSuper, TJS_W("Super class does not exist or cannot specify the super class"))
TJS_MSG_DECL_CONST(TJSInvalidOpecode, TJS_W("Invalid VM code"))
TJS_MSG_DECL_CONST(TJSRangeError, TJS_W("The value is out of the range"))
TJS_MSG_DECL_CONST(TJSAccessDenyed, TJS_W("Invalid operation for Read-only or Write-only property"))
TJS_MSG_DECL_CONST(TJSNativeClassCrash, TJS_W("Invalid object context"))
TJS_MSG_DECL_CONST(TJSInvalidObject, TJS_W("The object is already invalidated"))
TJS_MSG_DECL_CONST(TJSCannotOmit, TJS_W("\"...\" is used out of functions"))
TJS_MSG_DECL_CONST(TJSCannotParseDate, TJS_W("Invalid date format"))
TJS_MSG_DECL_CONST(TJSInvalidValueForTimestamp, TJS_W("Invalid value for date/time"))
TJS_MSG_DECL_CONST(TJSExceptionNotFound, TJS_W("Cannot convert exception because \"Exception\" does not exist"))
TJS_MSG_DECL_CONST(TJSInvalidFormatString, TJS_W("Invalid format string"))
TJS_MSG_DECL_CONST(TJSDivideByZero, TJS_W("Division by zero"))
TJS_MSG_DECL_CONST(TJSNotReconstructiveRandomizeData, TJS_W("Cannot reconstruct random seeds"))
TJS_MSG_DECL_CONST(TJSSymbol, TJS_W("ID"))
TJS_MSG_DECL_CONST(TJSCallHistoryIsFromOutOfTJS2Script, TJS_W("[out of TJS2 script]"))
TJS_MSG_DECL_CONST(TJSNObjectsWasNotFreed, TJS_W("Total %1 Object(s) was not freed"))
TJS_MSG_DECL_CONST(TJSObjectCreationHistoryDelimiter, TJS_W(" <-- "))
TJS_MSG_DECL_CONST(TJSObjectWasNotFreed, TJS_W("Object %1 [%2] wes not freed / The object was created at : %2"))
TJS_MSG_DECL_CONST(TJSGroupByObjectTypeAndHistory, TJS_W("Group by object type and location where the object was created"))
TJS_MSG_DECL_CONST(TJSGroupByObjectType, TJS_W("Group by object type"))
TJS_MSG_DECL_CONST(TJSObjectCountingMessageGroupByObjectTypeAndHistory, TJS_W("%1 time(s) : [%2] %3"))
TJS_MSG_DECL_CONST(TJSObjectCountingMessageTJSGroupByObjectType, TJS_W("%1 time(s) : [%2]"))
TJS_MSG_DECL_CONST(TJSWarnRunningCodeOnDeletingObject, TJS_W("%4: Running code on deleting-in-progress object %1[%2] / The object was created at : %3"))
TJS_MSG_DECL_CONST(TJSWriteError, TJS_W("Write error"))
TJS_MSG_DECL_CONST(TJSReadError, TJS_W("Read error"))
TJS_MSG_DECL_CONST(TJSSeekError, TJS_W("Seek error"))
TJS_MSG_DECL_CONST(TJSByteCodeBroken, TJS_W("Bytecode read error. File is broken or it's not bytecode file."))
TJS_MSG_DECL_CONST(TJSObjectHashMapLogVersionMismatch, TJS_W("Object Hash Map log version mismatch"))
TJS_MSG_DECL_CONST(TJSCurruptedObjectHashMapLog, TJS_W("Currupted Object Hash Map log"))
TJS_MSG_DECL_CONST(TJSUnknownFailure, TJS_W("Unknown failure : %08X"))
TJS_MSG_DECL_CONST(TJSUnknownPackUnpackTemplateCharcter, TJS_W("Unknown pack/unpack TEMPLATE charcter"))
TJS_MSG_DECL_CONST(TJSUnknownBitStringCharacter, TJS_W("Unknown bit string charcter"))
TJS_MSG_DECL_CONST(TJSUnknownHexStringCharacter, TJS_W("Unknown Hex string charcter"))
TJS_MSG_DECL_CONST(TJSNotSupportedUuencode, TJS_W("Not supported uuencode"))
TJS_MSG_DECL_CONST(TJSNotSupportedBER, TJS_W("Not supported BER"))
TJS_MSG_DECL_CONST(TJSNotSupportedUnpackLP, TJS_W("Not supported unpack \'p\'"))
TJS_MSG_DECL_CONST(TJSNotSupportedUnpackP, TJS_W("Not supported unpack \'P\'"))
#endif
