static const char __license[] = 
"吉里吉里[きりきり] SDL2 実行コア version %1 ( TJS version %2 )\n"
"Compiled on %DATE% %TIME%\n"
"Copyright (C) 2019-2021 Julian Uy\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a\n"
"copy of this software and associated documentation files (the \"Software\"),\n"
"to deal in the Software without restriction, including without limitation\n"
"the rights to use, copy, modify, merge, publish, distribute, sublicense,\n"
"and/or sell copies of the Software, and to permit persons to whom the\n"
"Software is furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in\n"
"all copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n"
"FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
"DEALINGS IN THE SOFTWARE.\n"
"\n"
"Additional licenses are listed below.\n"
"----------------------------------------------------------------------------\n"
"Copyright (c) 1997-2013 W.Dee and contributors All rights reserved.\n"
"Contributors\n"
" Go Watanabe, Kenjo, Kiyobee, Kouhei Yanagita, mey, MIK, Takenori Imoto, yun\n"
"Kirikiri Z Project Contributors\n"
"W.Dee, casper, 有限会社MCF, Biscrat, 青猫, nagai, ルー, 高際 雅之, 永劫,\n"
"ゆんゆん探偵, りょうご（今は無きあの星）, AZ-UME, 京 秋人,\n"
"Katsumasa Tsuneyoshi, 小池潤, miahmie, サークル獏, アザナシ, はっしぃ,\n"
"棚中製作所, わっふる/waffle, ワムソフト, TYPE-MOON, 有限会社エムツー,\n"
"Takenori Imoto\n"
"Kirikiri Z 64bit Project Contributors\n"
"合資会社ワムソフト, Takenori Imoto, 他\n"
"\n"
"吉里吉里Z実行コアの使用/配布/改変は、以下の条件に従ってください。\n"
"----------------------------------------------------------------------------\n"
"ソースコード形式かバイナリ形式か、変更するかしないかを問わず、以下の条件を満\n"
"たす場合に限り、再頒布および使用が許可されます。\n"
"\n"
"・ソースコードを再頒布する場合、上記の著作権表示、本条件一覧、および下記免責\n"
"  条項を含めること。\n"
"・バイナリ形式で再頒布する場合、頒布物に付属のドキュメント等の資料に、上記の\n"
"  著作権表示、本条件一覧、および下記免責条項を含めること。\n"
"・書面による特別の許可なしに、本ソフトウェアから派生した製品の宣伝または販売\n"
"  促進に、組織の名前またはコントリビューターの名前を使用してはならない。\n"
"\n"
"本ソフトウェアは、著作権者およびコントリビューターによって「現状のまま」提供\n"
"されており、明示黙示を問わず、商業的な使用可能性、および特定の目的に対する適\n"
"合性に関する暗黙の保証も含め、またそれに限定されない、いかなる保証もありませ\n"
"ん。著作権者もコントリビューターも、事由のいかんを問わず、損害発生の原因いか\n"
"んを問わず、かつ責任の根拠が契約であるか厳格責任であるか（過失その他の）不法\n"
"行為であるかを問わず、仮にそのような損害が発生する可能性を知らされていたとし\n"
"ても、本ソフトウェアの使用によって発生した（代替品または代用サービスの調達、\n"
"使用の喪失、データの喪失、利益の喪失、業務の中断も含め、またそれに限定されな\n"
"い）直接損害、間接損害、偶発的な損害、特別損害、懲罰的損害、または結果損害に\n"
"ついて、一切責任を負わないものとします。\n"
"\n"
"------------------------------------------------------------------------------\n"
"Thanks for many libraries, contributers and supporters not listible here.\n"
"This software is based in part on the work of Independent JPEG Group.\n"
"------------------------------------------------------------------------------\n"
"libjpeg-turbo\n"
"\n"
"Redistribution and use in source and binary forms, with or without modification,\n"
"are permitted provided that the following conditions are met:\n"
"\n"
"•	Redistributions of source code must retain the above copyright notice, this\n"
"list of conditions and the following disclaimer.\n"
"•	Redistributions in binary form must reproduce the above copyright notice,\n"
"this list of conditions and the following disclaimer in the documentation and/or\n"
"other materials provided with the distribution.\n"
"•	Neither the name of the libjpeg-turbo Project nor the names of its contributors\n"
"may be used to endorse or promote products derived from this software without\n"
"specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\", AND\n"
"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED\n"
"WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.\n"
"IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,\n"
"INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n"
"NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;  LOSS OF USE, DATA,\n"
"OR PROFITS;  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\n"
"OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED\n"
"OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------------\n"
"Using \"A C-program for MT19937\"\n"
"\n"
"   Copyright (C) 1997 - 2002, Makoto Matsumoto and Takuji Nishimura,\n"
"   All rights reserved.\n"
"\n"
"   Redistribution and use in source and binary forms, with or without\n"
"   modification, are permitted provided that the following conditions\n"
"   are met:\n"
"\n"
"     1. Redistributions of source code must retain the above copyright\n"
"        notice, this list of conditions and the following disclaimer.\n"
"\n"
"     2. Redistributions in binary form must reproduce the above copyright\n"
"        notice, this list of conditions and the following disclaimer in the\n"
"        documentation and/or other materials provided with the distribution.\n"
"\n"
"     3. The names of its contributors may not be used to endorse or promote\n"
"        products derived from this software without specific prior written\n"
"        permission.\n"
"\n"
"   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"   \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"   A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR\n"
"   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"   EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"   PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"   PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"   LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------------\n"
"libpng LICENSE\n"
"\n"
"This copy of the libpng notices is provided for your convenience.  In case of\n"
"any discrepancy between this copy and the notices in the file png.h that is\n"
"included in the libpng distribution, the latter shall prevail.\n"
"\n"
"COPYRIGHT NOTICE, DISCLAIMER, and LICENSE:\n"
"\n"
"If you modify libpng you may insert additional notices immediately following\n"
"this sentence.\n"
"\n"
"This code is released under the libpng license.\n"
"\n"
"libpng versions 1.2.6, August 15, 2004, through 1.6.1, March 28, 2013, are\n"
"Copyright (c) 2004, 2006-2012 Glenn Randers-Pehrson, and are\n"
"distributed according to the same disclaimer and license as libpng-1.2.5\n"
"with the following individual added to the list of Contributing Authors\n"
"\n"
"   Cosmin Truta\n"
"\n"
"libpng versions 1.0.7, July 1, 2000, through 1.2.5 - October 3, 2002, are\n"
"Copyright (c) 2000-2002 Glenn Randers-Pehrson, and are\n"
"distributed according to the same disclaimer and license as libpng-1.0.6\n"
"with the following individuals added to the list of Contributing Authors\n"
"\n"
"   Simon-Pierre Cadieux\n"
"   Eric S. Raymond\n"
"   Gilles Vollant\n"
"\n"
"and with the following additions to the disclaimer:\n"
"\n"
"   There is no warranty against interference with your enjoyment of the\n"
"   library or against infringement.  There is no warranty that our\n"
"   efforts or the library will fulfill any of your particular purposes\n"
"   or needs.  This library is provided with all faults, and the entire\n"
"   risk of satisfactory quality, performance, accuracy, and effort is with\n"
"   the user.\n"
"\n"
"libpng versions 0.97, January 1998, through 1.0.6, March 20, 2000, are\n"
"Copyright (c) 1998, 1999 Glenn Randers-Pehrson, and are\n"
"distributed according to the same disclaimer and license as libpng-0.96,\n"
"with the following individuals added to the list of Contributing Authors:\n"
"\n"
"   Tom Lane\n"
"   Glenn Randers-Pehrson\n"
"   Willem van Schaik\n"
"\n"
"libpng versions 0.89, June 1996, through 0.96, May 1997, are\n"
"Copyright (c) 1996, 1997 Andreas Dilger\n"
"Distributed according to the same disclaimer and license as libpng-0.88,\n"
"with the following individuals added to the list of Contributing Authors:\n"
"\n"
"   John Bowler\n"
"   Kevin Bracey\n"
"   Sam Bushell\n"
"   Magnus Holmgren\n"
"   Greg Roelofs\n"
"   Tom Tanner\n"
"\n"
"libpng versions 0.5, May 1995, through 0.88, January 1996, are\n"
"Copyright (c) 1995, 1996 Guy Eric Schalnat, Group 42, Inc.\n"
"\n"
"For the purposes of this copyright and license, \"Contributing Authors\"\n"
"is defined as the following set of individuals:\n"
"\n"
"   Andreas Dilger\n"
"   Dave Martindale\n"
"   Guy Eric Schalnat\n"
"   Paul Schmidt\n"
"   Tim Wegner\n"
"\n"
"The PNG Reference Library is supplied \"AS IS\".  The Contributing Authors\n"
"and Group 42, Inc. disclaim all warranties, expressed or implied,\n"
"including, without limitation, the warranties of merchantability and of\n"
"fitness for any purpose.  The Contributing Authors and Group 42, Inc.\n"
"assume no liability for direct, indirect, incidental, special, exemplary,\n"
"or consequential damages, which may result from the use of the PNG\n"
"Reference Library, even if advised of the possibility of such damage.\n"
"\n"
"Permission is hereby granted to use, copy, modify, and distribute this\n"
"source code, or portions hereof, for any purpose, without fee, subject\n"
"to the following restrictions:\n"
"\n"
"1. The origin of this source code must not be misrepresented.\n"
"\n"
"2. Altered versions must be plainly marked as such and must not\n"
"   be misrepresented as being the original source.\n"
"\n"
"3. This Copyright notice may not be removed or altered from any\n"
"   source or altered source distribution.\n"
"\n"
"The Contributing Authors and Group 42, Inc. specifically permit, without\n"
"fee, and encourage the use of this source code as a component to\n"
"supporting the PNG file format in commercial products.  If you use this\n"
"source code in a product, acknowledgment is not required but would be\n"
"appreciated.\n"
"\n"
"\n"
"A \"png_get_copyright\" function is available, for convenient use in \"about\"\n"
"boxes and the like:\n"
"\n"
"   printf(\"%s\",png_get_copyright(NULL));\n"
"\n"
"Also, the PNG logo (in PNG format, of course) is supplied in the\n"
"files \"pngbar.png\" and \"pngbar.jpg (88x31) and \"pngnow.png\" (98x31).\n"
"\n"
"Libpng is OSI Certified Open Source Software.  OSI Certified Open Source is a\n"
"certification mark of the Open Source Initiative.\n"
"\n"
"Glenn Randers-Pehrson\n"
"glennrp at users.sourceforge.net\n"
"March 28, 2013\n"
"------------------------------------------------------------------------------\n"
"zlib LICENSE\n"
"\n"
"  The deflate format used by zlib was defined by Phil Katz.  The deflate and\n"
"  zlib specifications were written by L.  Peter Deutsch.  Thanks to all the\n"
"  people who reported problems and suggested various improvements in zlib; they\n"
"  are too numerous to cite here.\n"
"\n"
"Copyright notice:\n"
"\n"
" (C) 1995-2012 Jean-loup Gailly and Mark Adler\n"
"\n"
"  This software is provided 'as-is', without any express or implied\n"
"  warranty.  In no event will the authors be held liable for any damages\n"
"  arising from the use of this software.\n"
"\n"
"  Permission is granted to anyone to use this software for any purpose,\n"
"  including commercial applications, and to alter it and redistribute it\n"
"  freely, subject to the following restrictions:\n"
"\n"
"  1. The origin of this software must not be misrepresented; you must not\n"
"     claim that you wrote the original software. If you use this software\n"
"     in a product, an acknowledgment in the product documentation would be\n"
"     appreciated but is not required.\n"
"  2. Altered source versions must be plainly marked as such, and must not be\n"
"     misrepresented as being the original software.\n"
"  3. This notice may not be removed or altered from any source distribution.\n"
"\n"
"  Jean-loup Gailly        Mark Adler\n"
"  jloup@gzip.org          madler@alumni.caltech.edu\n"
"\n"
"If you use the zlib library in a product, we would appreciate *not* receiving\n"
"lengthy legal documents to sign.  The sources are provided for free but without\n"
"warranty of any kind.  The library has been entirely written by Jean-loup\n"
"Gailly and Mark Adler; it does not include third-party code.\n"
"\n"
"If you redistribute modified sources, we would appreciate that you include in\n"
"the file ChangeLog history information documenting your changes.  Please read\n"
"the FAQ for more information on the distribution of modified source versions.\n"
"------------------------------------------------------------------------------\n"
"\n"
"Oniguruma LICENSE\n"
"-----------------\n"
"\n"
"/*-\n"
" * Copyright (c) 2002-2007  K.Kosako  <sndgk393 AT ybb DOT ne DOT jp>\n"
" * All rights reserved.\n"
" *\n"
" * Redistribution and use in source and binary forms, with or without\n"
" * modification, are permitted provided that the following conditions\n"
" * are met:\n"
" * 1. Redistributions of source code must retain the above copyright\n"
" *    notice, this list of conditions and the following disclaimer.\n"
" * 2. Redistributions in binary form must reproduce the above copyright\n"
" *    notice, this list of conditions and the following disclaimer in the\n"
" *    documentation and/or other materials provided with the distribution.\n"
" *\n"
" * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND\n"
" * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
" * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
" * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE\n"
" * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
" * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
" * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
" * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
" * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
" * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
" * SUCH DAMAGE.\n"
" */\n"
"------------------------------------------------------------------------------\n"
"                    The FreeType Project LICENSE\n"
"                    ----------------------------\n"
"\n"
"                            2006-Jan-27\n"
"\n"
"                    Copyright 1996-2002, 2006 by\n"
"          David Turner, Robert Wilhelm, and Werner Lemberg\n"
"\n"
"\n"
"\n"
"Introduction\n"
"============\n"
"\n"
"  The FreeType  Project is distributed in  several archive packages;\n"
"  some of them may contain, in addition to the FreeType font engine,\n"
"  various tools and  contributions which rely on, or  relate to, the\n"
"  FreeType Project.\n"
"\n"
"  This  license applies  to all  files found  in such  packages, and\n"
"  which do not  fall under their own explicit  license.  The license\n"
"  affects  thus  the  FreeType   font  engine,  the  test  programs,\n"
"  documentation and makefiles, at the very least.\n"
"\n"
"  This  license   was  inspired  by  the  BSD,   Artistic,  and  IJG\n"
"  (Independent JPEG  Group) licenses, which  all encourage inclusion\n"
"  and  use of  free  software in  commercial  and freeware  products\n"
"  alike.  As a consequence, its main points are that:\n"
"\n"
"    o We don't promise that this software works. However, we will be\n"
"      interested in any kind of bug reports. (`as is' distribution)\n"
"\n"
"    o You can  use this software for whatever you  want, in parts or\n"
"      full form, without having to pay us. (`royalty-free' usage)\n"
"\n"
"    o You may not pretend that  you wrote this software.  If you use\n"
"      it, or  only parts of it,  in a program,  you must acknowledge\n"
"      somewhere  in  your  documentation  that  you  have  used  the\n"
"      FreeType code. (`credits')\n"
"\n"
"  We  specifically  permit  and  encourage  the  inclusion  of  this\n"
"  software, with  or without modifications,  in commercial products.\n"
"  We  disclaim  all warranties  covering  The  FreeType Project  and\n"
"  assume no liability related to The FreeType Project.\n"
"\n"
"\n"
"  Finally,  many  people  asked  us  for  a  preferred  form  for  a\n"
"  credit/disclaimer to use in compliance with this license.  We thus\n"
"  encourage you to use the following text:\n"
"\n"
"   \"\"\"\n"
"    Portions of this software are copyright ｩ <year> The FreeType\n"
"    Project (www.freetype.org).  All rights reserved.\n"
"   \"\"\"\n"
"\n"
"  Please replace <year> with the value from the FreeType version you\n"
"  actually use.\n"
"\n"
"\n"
"Legal Terms\n"
"===========\n"
"\n"
"0. Definitions\n"
"--------------\n"
"\n"
"  Throughout this license,  the terms `package', `FreeType Project',\n"
"  and  `FreeType  archive' refer  to  the  set  of files  originally\n"
"  distributed  by the  authors  (David Turner,  Robert Wilhelm,  and\n"
"  Werner Lemberg) as the `FreeType Project', be they named as alpha,\n"
"  beta or final release.\n"
"\n"
"  `You' refers to  the licensee, or person using  the project, where\n"
"  `using' is a generic term including compiling the project's source\n"
"  code as  well as linking it  to form a  `program' or `executable'.\n"
"  This  program is  referred to  as  `a program  using the  FreeType\n"
"  engine'.\n"
"\n"
"  This  license applies  to all  files distributed  in  the original\n"
"  FreeType  Project,   including  all  source   code,  binaries  and\n"
"  documentation,  unless  otherwise  stated   in  the  file  in  its\n"
"  original, unmodified form as  distributed in the original archive.\n"
"  If you are  unsure whether or not a particular  file is covered by\n"
"  this license, you must contact us to verify this.\n"
"\n"
"  The FreeType  Project is copyright (C) 1996-2000  by David Turner,\n"
"  Robert Wilhelm, and Werner Lemberg.  All rights reserved except as\n"
"  specified below.\n"
"\n"
"1. No Warranty\n"
"--------------\n"
"\n"
"  THE FREETYPE PROJECT  IS PROVIDED `AS IS' WITHOUT  WARRANTY OF ANY\n"
"  KIND, EITHER  EXPRESS OR IMPLIED,  INCLUDING, BUT NOT  LIMITED TO,\n"
"  WARRANTIES  OF  MERCHANTABILITY   AND  FITNESS  FOR  A  PARTICULAR\n"
"  PURPOSE.  IN NO EVENT WILL ANY OF THE AUTHORS OR COPYRIGHT HOLDERS\n"
"  BE LIABLE  FOR ANY DAMAGES CAUSED  BY THE USE OR  THE INABILITY TO\n"
"  USE, OF THE FREETYPE PROJECT.\n"
"\n"
"2. Redistribution\n"
"-----------------\n"
"\n"
"  This  license  grants  a  worldwide, royalty-free,  perpetual  and\n"
"  irrevocable right  and license to use,  execute, perform, compile,\n"
"  display,  copy,   create  derivative  works   of,  distribute  and\n"
"  sublicense the  FreeType Project (in  both source and  object code\n"
"  forms)  and  derivative works  thereof  for  any  purpose; and  to\n"
"  authorize others  to exercise  some or all  of the  rights granted\n"
"  herein, subject to the following conditions:\n"
"\n"
"    o Redistribution of  source code  must retain this  license file\n"
"      (`FTL.TXT') unaltered; any  additions, deletions or changes to\n"
"      the original  files must be clearly  indicated in accompanying\n"
"      documentation.   The  copyright   notices  of  the  unaltered,\n"
"      original  files must  be  preserved in  all  copies of  source\n"
"      files.\n"
"\n"
"    o Redistribution in binary form must provide a  disclaimer  that\n"
"      states  that  the software is based in part of the work of the\n"
"      FreeType Team,  in  the  distribution  documentation.  We also\n"
"      encourage you to put an URL to the FreeType web page  in  your\n"
"      documentation, though this isn't mandatory.\n"
"\n"
"  These conditions  apply to any  software derived from or  based on\n"
"  the FreeType Project,  not just the unmodified files.   If you use\n"
"  our work, you  must acknowledge us.  However, no  fee need be paid\n"
"  to us.\n"
"\n"
"3. Advertising\n"
"--------------\n"
"\n"
"  Neither the  FreeType authors and  contributors nor you  shall use\n"
"  the name of the  other for commercial, advertising, or promotional\n"
"  purposes without specific prior written permission.\n"
"\n"
"  We suggest,  but do not require, that  you use one or  more of the\n"
"  following phrases to refer  to this software in your documentation\n"
"  or advertising  materials: `FreeType Project',  `FreeType Engine',\n"
"  `FreeType library', or `FreeType Distribution'.\n"
"\n"
"  As  you have  not signed  this license,  you are  not  required to\n"
"  accept  it.   However,  as  the FreeType  Project  is  copyrighted\n"
"  material, only  this license, or  another one contracted  with the\n"
"  authors, grants you  the right to use, distribute,  and modify it.\n"
"  Therefore,  by  using,  distributing,  or modifying  the  FreeType\n"
"  Project, you indicate that you understand and accept all the terms\n"
"  of this license.\n"
"\n"
"4. Contacts\n"
"-----------\n"
"\n"
"  There are two mailing lists related to FreeType:\n"
"\n"
"    o freetype@nongnu.org\n"
"\n"
"      Discusses general use and applications of FreeType, as well as\n"
"      future and  wanted additions to the  library and distribution.\n"
"      If  you are looking  for support,  start in  this list  if you\n"
"      haven't found anything to help you in the documentation.\n"
"\n"
"    o freetype-devel@nongnu.org\n"
"\n"
"      Discusses bugs,  as well  as engine internals,  design issues,\n"
"      specific licenses, porting, etc.\n"
"\n"
"  Our home page can be found at\n"
"\n"
"    http://www.freetype.org\n"
"------------------------------------------------------------------------------\n"
"picojson LICENSE\n"
"\n"
"/* Copyright 2009 Cybozu Labs, Inc.\n"
" *\n"
" * Redistribution and use in source and binary forms, with or without\n"
" * modification, are permitted provided that the following conditions are met:\n"
" *\n"
" * 1. Redistributions of source code must retain the above copyright notice,\n"
" *    this list of conditions and the following disclaimer.\n"
" * 2. Redistributions in binary form must reproduce the above copyright notice,\n"
" *    this list of conditions and the following disclaimer in the documentation\n"
" *    and/or other materials provided with the distribution.\n"
" *\n"
" * THIS SOFTWARE IS PROVIDED BY CYBOZU LABS, INC. ``AS IS'' AND ANY EXPRESS OR\n"
" * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n"
" * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO\n"
" * EVENT SHALL CYBOZU LABS, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,\n"
" * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES\n"
" * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
" * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND\n"
" * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
" * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF\n"
" * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
" *\n"
" * The views and conclusions contained in the software and documentation are\n"
" * those of the authors and should not be interpreted as representing official\n"
" * policies, either expressed or implied, of Cybozu Labs, Inc.\n"
" *\n"
" */\n"
"\n"
"------------------------------------------------------------------------------\n"
"\n"
"   Copyright (c) 2012, The Android Open Source Project\n"
"\n"
"   Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"   you may not use this file except in compliance with the License.\n"
"\n"
"   Unless required by applicable law or agreed to in writing, software\n"
"   distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"   See the License for the specific language governing permissions and\n"
"   limitations under the License.\n"
"\n"
"\n"
"                                 Apache License\n"
"                           Version 2.0, January 2004\n"
"                        http://www.apache.org/licenses/\n"
"\n"
"   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n"
"\n"
"   1. Definitions.\n"
"\n"
"      \"License\" shall mean the terms and conditions for use, reproduction,\n"
"      and distribution as defined by Sections 1 through 9 of this document.\n"
"\n"
"      \"Licensor\" shall mean the copyright owner or entity authorized by\n"
"      the copyright owner that is granting the License.\n"
"\n"
"      \"Legal Entity\" shall mean the union of the acting entity and all\n"
"      other entities that control, are controlled by, or are under common\n"
"      control with that entity. For the purposes of this definition,\n"
"      \"control\" means (i) the power, direct or indirect, to cause the\n"
"      direction or management of such entity, whether by contract or\n"
"      otherwise, or (ii) ownership of fifty percent (50%) or more of the\n"
"      outstanding shares, or (iii) beneficial ownership of such entity.\n"
"\n"
"      \"You\" (or \"Your\") shall mean an individual or Legal Entity\n"
"      exercising permissions granted by this License.\n"
"\n"
"      \"Source\" form shall mean the preferred form for making modifications,\n"
"      including but not limited to software source code, documentation\n"
"      source, and configuration files.\n"
"\n"
"      \"Object\" form shall mean any form resulting from mechanical\n"
"      transformation or translation of a Source form, including but\n"
"      not limited to compiled object code, generated documentation,\n"
"      and conversions to other media types.\n"
"\n"
"      \"Work\" shall mean the work of authorship, whether in Source or\n"
"      Object form, made available under the License, as indicated by a\n"
"      copyright notice that is included in or attached to the work\n"
"      (an example is provided in the Appendix below).\n"
"\n"
"      \"Derivative Works\" shall mean any work, whether in Source or Object\n"
"      form, that is based on (or derived from) the Work and for which the\n"
"      editorial revisions, annotations, elaborations, or other modifications\n"
"      represent, as a whole, an original work of authorship. For the purposes\n"
"      of this License, Derivative Works shall not include works that remain\n"
"      separable from, or merely link (or bind by name) to the interfaces of,\n"
"      the Work and Derivative Works thereof.\n"
"\n"
"      \"Contribution\" shall mean any work of authorship, including\n"
"      the original version of the Work and any modifications or additions\n"
"      to that Work or Derivative Works thereof, that is intentionally\n"
"      submitted to Licensor for inclusion in the Work by the copyright owner\n"
"      or by an individual or Legal Entity authorized to submit on behalf of\n"
"      the copyright owner. For the purposes of this definition, \"submitted\"\n"
"      means any form of electronic, verbal, or written communication sent\n"
"      to the Licensor or its representatives, including but not limited to\n"
"      communication on electronic mailing lists, source code control systems,\n"
"      and issue tracking systems that are managed by, or on behalf of, the\n"
"      Licensor for the purpose of discussing and improving the Work, but\n"
"      excluding communication that is conspicuously marked or otherwise\n"
"      designated in writing by the copyright owner as \"Not a Contribution.\"\n"
"\n"
"      \"Contributor\" shall mean Licensor and any individual or Legal Entity\n"
"      on behalf of whom a Contribution has been received by Licensor and\n"
"      subsequently incorporated within the Work.\n"
"\n"
"   2. Grant of Copyright License. Subject to the terms and conditions of\n"
"      this License, each Contributor hereby grants to You a perpetual,\n"
"      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
"      copyright license to reproduce, prepare Derivative Works of,\n"
"      publicly display, publicly perform, sublicense, and distribute the\n"
"      Work and such Derivative Works in Source or Object form.\n"
"\n"
"   3. Grant of Patent License. Subject to the terms and conditions of\n"
"      this License, each Contributor hereby grants to You a perpetual,\n"
"      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
"      (except as stated in this section) patent license to make, have made,\n"
"      use, offer to sell, sell, import, and otherwise transfer the Work,\n"
"      where such license applies only to those patent claims licensable\n"
"      by such Contributor that are necessarily infringed by their\n"
"      Contribution(s) alone or by combination of their Contribution(s)\n"
"      with the Work to which such Contribution(s) was submitted. If You\n"
"      institute patent litigation against any entity (including a\n"
"      cross-claim or counterclaim in a lawsuit) alleging that the Work\n"
"      or a Contribution incorporated within the Work constitutes direct\n"
"      or contributory patent infringement, then any patent licenses\n"
"      granted to You under this License for that Work shall terminate\n"
"      as of the date such litigation is filed.\n"
"\n"
"   4. Redistribution. You may reproduce and distribute copies of the\n"
"      Work or Derivative Works thereof in any medium, with or without\n"
"      modifications, and in Source or Object form, provided that You\n"
"      meet the following conditions:\n"
"\n"
"      (a) You must give any other recipients of the Work or\n"
"          Derivative Works a copy of this License; and\n"
"\n"
"      (b) You must cause any modified files to carry prominent notices\n"
"          stating that You changed the files; and\n"
"\n"
"      (c) You must retain, in the Source form of any Derivative Works\n"
"          that You distribute, all copyright, patent, trademark, and\n"
"          attribution notices from the Source form of the Work,\n"
"          excluding those notices that do not pertain to any part of\n"
"          the Derivative Works; and\n"
"\n"
"      (d) If the Work includes a \"NOTICE\" text file as part of its\n"
"          distribution, then any Derivative Works that You distribute must\n"
"          include a readable copy of the attribution notices contained\n"
"          within such NOTICE file, excluding those notices that do not\n"
"          pertain to any part of the Derivative Works, in at least one\n"
"          of the following places: within a NOTICE text file distributed\n"
"          as part of the Derivative Works; within the Source form or\n"
"          documentation, if provided along with the Derivative Works; or,\n"
"          within a display generated by the Derivative Works, if and\n"
"          wherever such third-party notices normally appear. The contents\n"
"          of the NOTICE file are for informational purposes only and\n"
"          do not modify the License. You may add Your own attribution\n"
"          notices within Derivative Works that You distribute, alongside\n"
"          or as an addendum to the NOTICE text from the Work, provided\n"
"          that such additional attribution notices cannot be construed\n"
"          as modifying the License.\n"
"\n"
"      You may add Your own copyright statement to Your modifications and\n"
"      may provide additional or different license terms and conditions\n"
"      for use, reproduction, or distribution of Your modifications, or\n"
"      for any such Derivative Works as a whole, provided Your use,\n"
"      reproduction, and distribution of the Work otherwise complies with\n"
"      the conditions stated in this License.\n"
"\n"
"   5. Submission of Contributions. Unless You explicitly state otherwise,\n"
"      any Contribution intentionally submitted for inclusion in the Work\n"
"      by You to the Licensor shall be under the terms and conditions of\n"
"      this License, without any additional terms or conditions.\n"
"      Notwithstanding the above, nothing herein shall supersede or modify\n"
"      the terms of any separate license agreement you may have executed\n"
"      with Licensor regarding such Contributions.\n"
"\n"
"   6. Trademarks. This License does not grant permission to use the trade\n"
"      names, trademarks, service marks, or product names of the Licensor,\n"
"      except as required for reasonable and customary use in describing the\n"
"      origin of the Work and reproducing the content of the NOTICE file.\n"
"\n"
"   7. Disclaimer of Warranty. Unless required by applicable law or\n"
"      agreed to in writing, Licensor provides the Work (and each\n"
"      Contributor provides its Contributions) on an \"AS IS\" BASIS,\n"
"      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n"
"      implied, including, without limitation, any warranties or conditions\n"
"      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A\n"
"      PARTICULAR PURPOSE. You are solely responsible for determining the\n"
"      appropriateness of using or redistributing the Work and assume any\n"
"      risks associated with Your exercise of permissions under this License.\n"
"\n"
"   8. Limitation of Liability. In no event and under no legal theory,\n"
"      whether in tort (including negligence), contract, or otherwise,\n"
"      unless required by applicable law (such as deliberate and grossly\n"
"      negligent acts) or agreed to in writing, shall any Contributor be\n"
"      liable to You for damages, including any direct, indirect, special,\n"
"      incidental, or consequential damages of any character arising as a\n"
"      result of this License or out of the use or inability to use the\n"
"      Work (including but not limited to damages for loss of goodwill,\n"
"      work stoppage, computer failure or malfunction, or any and all\n"
"      other commercial damages or losses), even if such Contributor\n"
"      has been advised of the possibility of such damages.\n"
"\n"
"   9. Accepting Warranty or Additional Liability. While redistributing\n"
"      the Work or Derivative Works thereof, You may choose to offer,\n"
"      and charge a fee for, acceptance of support, warranty, indemnity,\n"
"      or other liability obligations and/or rights consistent with this\n"
"      License. However, in accepting such obligations, You may act only\n"
"      on Your own behalf and on Your sole responsibility, not on behalf\n"
"      of any other Contributor, and only if You agree to indemnify,\n"
"      defend, and hold each Contributor harmless for any liability\n"
"      incurred by, or claims asserted against, such Contributor by reason\n"
"      of your accepting any such warranty or additional liability.\n"
"\n"
"   END OF TERMS AND CONDITIONS\n"
"\n"
"------------------------------------------------------------------------------\n"
"Microsoft Corporation Technical Documentation License Agreement for the specification “JPEG XR Device Porting Kit”\n"
"Copyright (c) 2013 Microsoft Corp.\n"
"All rights reserved.\n"
"Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:\n"
" Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.\n"
" Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THEIMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSEARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BELIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, ORCONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OFSUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESSINTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER INCONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THEPOSSIBILITY OF SUCH DAMAGE..\n"
"----------------------------------------------------------------------------\n"
"------------------------------------------------------------------------\n"
"*** vorbis\n"
"*** ogg\n"
"\n"
"Copyright (c) 1994-2004 Xiph.org Foundation\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"  notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"  notice, this list of conditions and the following disclaimer in the\n"
"  documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of the Xiph.org Foundation nor the names of its\n"
"  contributors may be used to endorse or promote products derived from\n"
"  this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"------------------------------------------------------------------------\n"
"*** theora\n"
"\n"
"Copyright (C) 2002-2008 Xiph.org Foundation and contributors.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of the Xiph.org Foundation nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"------------------------------------------------------------------------\n"
"*** libfishsound\n"
"*** dsfSeeking\n"
"\n"
"Copyright (C) 2003, 2004 Commonwealth Scientific and Industrial Research\n"
"  Organisation (CSIRO) Australia\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of the CSIRO Australia nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE ORGANISATION OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"------------------------------------------------------------------------\n"
"*** libCMMLParse\n"
"*** libCMMLTags\n"
"*** libCMMLTagsDotNET\n"
"*** libOOOggChef\n"
"*** libTemporalURI\n"
"*** libWinCMMLParse\n"
"*** dsfCMMLDecoder\n"
"*** dsfAnxDemux\n"
"*** AnxCutter\n"
"*** CMMLDump\n"
"*** mod_oggchef\n"
"\n"
"Copyright (C) 2003-2005 Zentaro Kavanagh\n"
"\n"
"Copyright (C) 2003-2005 Commonwealth Scientific and Industrial Research\n"
"  Organisation (CSIRO) Australia\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of CSIRO Australia nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE ORGANISATION OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"------------------------------------------------------------------------\n"
"*** dsfOggDemux\n"
"*** dsfOggMux\n"
"*** dsfSpeexDecoder\n"
"*** dsfSpeexEncoder\n"
"*** dsfVorbisDecoder\n"
"*** dsfVorbisEncoder\n"
"*** dsfFLACDecoder\n"
"*** dsfFLACEncoder\n"
"*** dsfTheoraDecoder\n"
"*** dsfTheoraEncoder\n"
"*** dsfAbstractAudioDecoder\n"
"*** dsfAbstractAudioEncoder\n"
"*** dsfAbstractVideoDecoder\n"
"*** dsfAbstractVideoEncoder\n"
"*** dsfSubtitleVMR9\n"
"*** libiWrapper\n"
"*** libilliCore\n"
"*** libOOTheora\n"
"*** libOOOgg\n"
"*** libOOOggSeek\n"
"*** libVorbisComment\n"
"*** libVorbisCommentDotNET\n"
"*** OOOggDump\n"
"*** OOOggStat\n"
"*** OOOggCommentDump\n"
"*** CLOgg\n"
"*** DNPlay\n"
"*** iOCE\n"
"\n"
"Copyright (C) 2008-2010 Cristian Adam\n"
"Copyright (C) 2003-2005 Zentaro Kavanagh\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"  notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"  notice, this list of conditions and the following disclaimer in the\n"
"  documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of Zentaro Kavanagh nor the names of contributors\n"
"  may be used to endorse or promote products derived from this software\n"
"  without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n"
"PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE ORGANISATION OR\n"
"CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"------------------------------------------------------------------------\n"
"wcschr\n"
"Copyright (c) 2002 Tim J. Robbins All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"1. Redistributions of source code must retain the above copyright\n"
"   notice, this list of conditions and the following disclaimer.\n"
"2. Redistributions in binary form must reproduce the above copyright\n"
"   notice, this list of conditions and the following disclaimer in the\n"
"   documentation and/or other materials provided with the distribution.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND\n"
"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE\n"
"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
"LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
"OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
"SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"wcsstr wcscat wcsstr wcstod wcsspn\n"
"Copyright (c)1999 Citrus Project, All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"1. Redistributions of source code must retain the above copyright\n"
"   notice, this list of conditions and the following disclaimer.\n"
"2. Redistributions in binary form must reproduce the above copyright\n"
"   notice, this list of conditions and the following disclaimer in the\n"
"   documentation and/or other materials provided with the distribution.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND\n"
"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE\n"
"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
"LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
"OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
"SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"wcscmp wcsncmp wcsncpy\n"
"Copyright (c) 1990, 1993\n"
"The Regents of the University of California.  All rights reserved.\n"
"\n"
"This code is derived from software contributed to Berkeley by\n"
"Chris Torek.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"1. Redistributions of source code must retain the above copyright\n"
"   notice, this list of conditions and the following disclaimer.\n"
"2. Redistributions in binary form must reproduce the above copyright\n"
"   notice, this list of conditions and the following disclaimer in the\n"
"   documentation and/or other materials provided with the distribution.\n"
"3. Neither the name of the University nor the names of its contributors\n"
"   may be used to endorse or promote products derived from this software\n"
"   without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND\n"
"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE\n"
"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
"LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
"OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
"SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"wcsftime\n"
"Based on the UCB version with the ID appearing below.\n"
"This is ANSIish only when \"multibyte character == plain character\".\n"
"\n"
"Copyright (c) 1989, 1993\n"
"The Regents of the University of California.  All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"1. Redistributions of source code must retain the above copyright\n"
"   notice, this list of conditions and the following disclaimer.\n"
"2. Redistributions in binary form must reproduce the above copyright\n"
"   notice, this list of conditions and the following disclaimer in the\n"
"   documentation and/or other materials provided with the distribution.\n"
"3. Neither the name of the University nor the names of its contributors\n"
"   may be used to endorse or promote products derived from this software\n"
"   without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND\n"
"ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
"IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
"ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE\n"
"FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
"DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n"
"OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
"HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
"LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n"
"OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n"
"SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"libogg license\n"
"Copyright (c) 2002, Xiph.org Foundation\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of the Xiph.org Foundation nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"opus license\n"
"Copyright 2001-2011 Xiph.Org, Skype Limited, Octasic,\n"
"                    Jean-Marc Valin, Timothy B. Terriberry,\n"
"                    CSIRO, Gregory Maxwell, Mark Borgerding,\n"
"                    Erik de Castro Lopo\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of Internet Society, IETF or IETF Trust, nor the\n"
"names of specific contributors, may be used to endorse or promote\n"
"products derived from this software without specific prior written\n"
"permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER\n"
"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
"EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,\n"
"PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR\n"
"PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
"LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
"NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
"SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
"Opus is subject to the royalty-free patent licenses which are\n"
"specified at:\n"
"\n"
"Xiph.Org Foundation:\n"
"https://datatracker.ietf.org/ipr/1524/\n"
"\n"
"Microsoft Corporation:\n"
"https://datatracker.ietf.org/ipr/1914/\n"
"\n"
"Broadcom Corporation:\n"
"https://datatracker.ietf.org/ipr/1526/\n"
"------------------------------------------------------------------------\n"
"opusfile license\n"
"Copyright (c) 1994-2013 Xiph.Org Foundation and contributors\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions\n"
"are met:\n"
"\n"
"- Redistributions of source code must retain the above copyright\n"
"notice, this list of conditions and the following disclaimer.\n"
"\n"
"- Redistributions in binary form must reproduce the above copyright\n"
"notice, this list of conditions and the following disclaimer in the\n"
"documentation and/or other materials provided with the distribution.\n"
"\n"
"- Neither the name of the Xiph.Org Foundation nor the names of its\n"
"contributors may be used to endorse or promote products derived from\n"
"this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
"OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"ANGLE license\n"
"// Copyright (C) 2002-2013 The ANGLE Project Authors.\n"
"// Portions Copyright (C) Microsoft Corporation.\n"
"//\n"
"// BSD License\n"
"//\n"
"// All rights reserved.\n"
"//\n"
"// Redistribution and use in source and binary forms, with or without\n"
"// modification, are permitted provided that the following conditions\n"
"// are met:\n"
"//\n"
"//     Redistributions of source code must retain the above copyright\n"
"//     notice, this list of conditions and the following disclaimer.\n"
"//\n"
"//     Redistributions in binary form must reproduce the above\n"
"//     copyright notice, this list of conditions and the following\n"
"//     disclaimer in the documentation and/or other materials provided\n"
"//     with the distribution.\n"
"//\n"
"//     Neither the name of TransGaming Inc., Google Inc., 3DLabs Inc.\n"
"//     Ltd., Microsoft Corporation, nor the names of their contributors\n"
"//     may be used to endorse or promote products derived from this\n"
"//     software without specific prior written permission.\n"
"//\n"
"// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"// \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n"
"// FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n"
"// COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
"// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n"
"// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
"// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
"// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n"
"// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n"
"// ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
"// POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"simde license\n"
"Copyright (c) 2017 Evan Nemerson <evan@nemerson.com>\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining\n"
"a copy of this software and associated documentation files (the\n"
"\"Software\"), to deal in the Software without restriction, including\n"
"without limitation the rights to use, copy, modify, merge, publish,\n"
"distribute, sublicense, and/or sell copies of the Software, and to\n"
"permit persons to whom the Software is furnished to do so, subject to\n"
"the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be\n"
"included in all copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n"
"EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
"MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n"
"NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n"
"LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\n"
"OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\n"
"WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"------------------------------------------------------------------------\n"
"SDL2 license\n"
"Copyright (C) 1997-2021 Sam Lantinga <slouken@libsdl.org>\n"
"\n"
"This software is provided 'as-is', without any express or implied\n"
"warranty.  In no event will the authors be held liable for any damages\n"
"arising from the use of this software.\n"
"\n"
"Permission is granted to anyone to use this software for any purpose,\n"
"including commercial applications, and to alter it and redistribute it\n"
"freely, subject to the following restrictions:\n"
"\n"
"1. The origin of this software must not be misrepresented; you must not\n"
"   claim that you wrote the original software. If you use this software\n"
"   in a product, an acknowledgment in the product documentation would be\n"
"   appreciated but is not required.\n"
"2. Altered source versions must be plainly marked as such, and must not be\n"
"   misrepresented as being the original software.\n"
"3. This notice may not be removed or altered from any source distribution.\n"
"------------------------------------------------------------------------\n"
"krglhwebp license\n"
"Copyright (c) 2019 Julian Uy\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a\n"
"copy of this software and associated documentation files (the \"Software\"),\n"
"to deal in the Software without restriction, including without limitation\n"
"the rights to use, copy, modify, merge, publish, distribute, sublicense,\n"
"and/or sell copies of the Software, and to permit persons to whom the\n"
"Software is furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in\n"
"all copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n"
"FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
"DEALINGS IN THE SOFTWARE.\n"
"------------------------------------------------------------------------\n"
"libwebp license\n"
"Copyright (c) 2010, Google Inc. All rights reserved.\n"
"\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are\n"
"met:\n"
"\n"
"  * Redistributions of source code must retain the above copyright\n"
"    notice, this list of conditions and the following disclaimer.\n"
"\n"
"  * Redistributions in binary form must reproduce the above copyright\n"
"    notice, this list of conditions and the following disclaimer in\n"
"    the documentation and/or other materials provided with the\n"
"    distribution.\n"
"\n"
"  * Neither the name of Google nor the names of its contributors may\n"
"    be used to endorse or promote products derived from this software\n"
"    without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
"HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"------------------------------------------------------------------------\n"
"\n";